# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_VERSION = "2"

Vagrant.configure(VAGRANTFILE_VERSION) do |config|

  config.vm.box = "bento/ubuntu-18.04"
  config.vm.hostname = "ansible-tema09"
  config.vm.network "private_network", ip: "55.55.55.5"
  config.vm.provision :shell, :path => "installAnsible.sh"

  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "playbook.yml"
     ansible.version = "2.8.2"

  end
end
